<#
generate_iss.ps1

Generates an Inno Setup script using installer_settings.json values.
Outputs: video_pipeline_installer_generated.iss

Usage:
  .\generate_iss.ps1 -Settings .\installer_settings.json -Out .\video_pipeline_installer_generated.iss
#>
param(
    [string]$Settings = "installer_settings.json",
    [string]$Out = "video_pipeline_installer_generated.iss"
)

function Write-Log { param($m) Write-Host "[$((Get-Date).ToString('s'))] $m" }

if (-not (Test-Path $Settings)) { Write-Log "Settings file not found: $Settings"; exit 1 }
$cfg = Get-Content $Settings -Raw | ConvertFrom-Json

$appName = $cfg.appName -or 'Video Pipeline'
$appVersion = $cfg.version -or '1.0.0'
$defaultDir = $cfg.installDir -replace '\\\\','\\' -replace '\$env:ProgramFiles','{pf}'
if (-not $defaultDir) { $defaultDir = '{pf}\\VideoPipeline' }

$excludes = @()
if ($cfg.excludePatterns) {
    foreach ($p in $cfg.excludePatterns) { $excludes += $p }
}
$exclLine = ($excludes -join ';')

$iss = @"
; Generated by generate_iss.ps1
[Setup]
AppName={$appName}
AppVersion={$appVersion}
DefaultDirName={$defaultDir}
DefaultGroupName={$appName}
Compression=lzma
SolidCompression=yes
OutputBaseFilename=VideoPipeline_Installer

[Files]
Source: "*"; DestDir: "{app}"; Flags: recursesubdirs createallsubdirs; Excludes: "{$exclLine}"

[Icons]
Name: "{group}\{$appName}"; Filename: "{app}\pipeline-gui.exe"; WorkingDir: "{app}"
Name: "{group}\Uninstall {$appName}"; Filename: "{uninstallexe}"; WorkingDir: "{app}"

[Run]
Filename: "powershell.exe"; Parameters: "-ExecutionPolicy Bypass -NoProfile -File \"{app}\\installer.ps1\""; Flags: runhidden

[UninstallDelete]
Type: filesandordirs; Name: "{app}"
"@

$iss | Out-File -FilePath $Out -Encoding UTF8
Write-Log "Generated ISS: $Out"
